favicon_ico: /assets/images/favicons/favicon.ico
favicon_png: /assets/images/favicons/favicon.png
favicon_svg: /assets/images/favicons/arbutus-tree-black.svg
manifest:
  name: Arbutus Code
  short_name: Arbutus
  theme_color: "#BF5841"
  background_color: "#ffffff"
  display: standalone
