require 'yaml'

# Jekyll plugin to generate _sass/_brand.scss from _data/brand_colors.yml
# This runs during the Jekyll build process, including in GitHub Actions

Jekyll::Hooks.register :site, :after_init do |site|
  yaml_path = File.join(site.source, '_data', 'brand_colors.yml')
  
  scss_path = File.join(site.source, '_sass', '_brand.scss')
  
  if File.exist?(yaml_path)
    begin
      colors = YAML.load_file(yaml_path)
      
      scss_content = "// Brand Palette - Generated from _data/brand_colors.yml\n"
      scss_content += "// DO NOT EDIT THIS FILE DIRECTLY - Make changes in the admin panel or _data/brand_colors.yml\n\n"
      
      colors.each do |name, value|
        scss_content += "$#{name}: #{value} !default;\n"
      end
      
      File.write(scss_path, scss_content)
      Jekyll.logger.info "Brand Colors:", "Generated _sass/_brand.scss from _data/brand_colors.yml"
    rescue => e
      Jekyll.logger.error "Brand Colors:", "Error generating _sass/_brand.scss: #{e.message}"
    end
  else
    Jekyll.logger.warn "Brand Colors:", "_data/brand_colors.yml not found, skipping SCSS generation"
  end
end
