backend:
  name: github
  repo: Arbutus-Code/arbutus-jekyll-demo # Ensure this is your target repo
  branch: main # Ensure this is your target branch
  base_url: https://oauth.arbutuscode.ca
  auth_endpoint: auth
  site_domain: https://jekyll.arbutuscode.ca

media_folder: "assets/images/uploads" # Decap requires this
public_folder: "/assets/images/uploads" # Decap requires this

collections:
  - name: "test_posts"
    label: "Test Posts"
    folder: "_test_posts" # A temporary folder for testing
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
